--table 1:
CREATE TABLE Bibliotheque (
    Bibliotheque_id NUMBER GENERATED BY DEFAULT AS IDENTITY ,
    nomBibliotheque VARCHAR2(255),
    adresseBibliotheque VARCHAR2(255),
    numero_telephone VARCHAR2(255),
    email  VARCHAR2(255),
  PRIMARY KEY(Bibliotheque_id)
 );

--table 2:
 CREATE TABLE Adherent (
    adherent_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR2(255),
    Prenom VARCHAR2(255),
    dateNaissance DATE,
    email VARCHAR2(255),
    adresse VARCHAR2(255),
    dateInscription DATE,
    nombreEmpruntsEnCour NUMBER,
    fk_Bibliotheque_id NUMBER NOT NULL,
    FOREIGN KEY(fk_Bibliotheque_id) REFERENCES Bibliotheque(Bibliotheque_id)on delete cascade,
    PRIMARY KEY(adherent_id)
 );

 --table 3:
 CREATE  TABLE   Document(
     document_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
     titre VARCHAR2(255),
     prix FLOAT,
     type_document  VARCHAR2(255),
     fk_Bibliotheque_id NUMBER NOT NULL,
     PRIMARY KEY(document_id),
     FOREIGN KEY(fk_Bibliotheque_id) REFERENCES Bibliotheque(Bibliotheque_id) on delete cascade
 );

 --table 4:
 CREATE TABLE  Volume(
     volume_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
     auteur VARCHAR2(255),
     nbrPage NUMBER,
     type_volume VARCHAR2(255),
     fk_Document_id  NUMBER NOT NULL,
     PRIMARY KEY(volume_id),
     FOREIGN KEY(fk_Document_id) REFERENCES  Document(Document_id) on delete cascade
 );

 --table 5:
 CREATE TABLE Livre (
     livre_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
     disponible VARCHAR2(255),
     fk_adherent_id NUMBER NOT NULL,
     fk_volume_id NUMBER NOT NULL,
     FOREIGN KEY(fk_adherent_id) REFERENCES Adherent(adherent_id) on delete cascade,
     FOREIGN KEY(fk_volume_id) REFERENCES Volume(volume_id)on delete cascade,
     PRIMARY KEY(livre_id)
 );

  --table 6:
  CREATE TABLE Emprunte (
   adherent_id NUMBER NOT NULL,
   livre_id NUMBER NOT NULL,
   date_emprunt Date,
   date_retour DATE,
   fk_adherent NUMBER NOT NULL,
   fk_livre NUMBER NOT NULL,
   PRIMARY KEY(Adherent_id,livre_id),
   FOREIGN KEY(fk_adherent) REFERENCES  Adherent(Adherent_id)on delete cascade,
   FOREIGN KEY(fk_livre) REFERENCES Livre(livre_id)on delete cascade
  );

 --table 7:
  CREATE TABLE Dictionnaire (
      dictionnaire_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
      fk_volume_id NUMBER NOT NULL,
      FOREIGN KEY(fk_volume_id) REFERENCES Volume(volume_id)on delete cascade,
      PRIMARY KEY(dictionnaire_id)
  );

--table 8:
 CREATE TABLE  BD(
     BD_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
     dessinateur VARCHAR2(255) ,
     fk_volume_id NUMBER NOT NULL,
     FOREIGN KEY(fk_volume_id) REFERENCES  Volume(volume_id)on delete cascade,
     PRIMARY KEY(BD_id)
 );


--table 9:
 CREATE TABLE  Journal(
     journal_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
     date_parution Date,
     fk_Document_id  NUMBER NOT NULL,
     FOREIGN KEY(fk_Document_id) REFERENCES  Document(Document_id)on delete cascade,
     PRIMARY KEY(journal_id)
 );
